name: Fetch YouTube Transcript

on:
  workflow_dispatch:

jobs:
  fetch-transcript:
    runs-on: ubuntu-latest

    permissions:
      contents: write # REQUIRED for pushing commits

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
          
      

      - name: Run transcript script
        env:
          PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
          PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
          PSQL_PASSWORD: ${{ secrets.PSQL_PASSWORD }}
          PSQL_USERNAME: ${{ secrets.PSQL_USERNAME }}
          PSQL_HOST: ${{ secrets.PSQL_HOST }}
        run: |
          python youtube_transcript.py
          python insert_into_vector_db.py
          python search_from_vector_db.py "database optimization"

      - name: Commit transcript file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add *.txt

          # Commit only if there are changes
          git diff --quiet && git diff --staged --quiet || \
            git commit -m "Add YouTube transcript"

          git push

      - name: Upload transcript as artifact
        uses: actions/upload-artifact@v4
        with:
          name: youtube-transcript
          path: "*.txt"
